export const GET_PIZZAS_REQUEST = 'GET_PIZZAS_REQUEST';
export const GET_PIZZAS_SUCCESS = 'GET_PIZZAS_SUCCESS';
export const GET_PIZZAS_FAIL = 'GET_PIZZAS_FAIL';

export const ADD_PIZZA_REQUEST = 'ADD_PIZZA_REQUEST';
export const ADD_PIZZA_SUCCESS = 'ADD_PIZZA_SUCCESS';
export const ADD_PIZZA_FAIL = 'ADD_PIZZA_FAIL';

export const RESET_STATE = 'RESET_STATE';

export const GET_PIZZA_BY_ID_REQUEST = 'GET_PIZZA_BY_ID_REQUEST';
export const GET_PIZZA_BY_ID_SUCCESS = 'GET_PIZZA_BY_ID_SUCCESS';
export const GET_PIZZA_BY_ID_FAIL = 'GET_PIZZA_BY_ID_FAIL';
